INSERT INTO CITY VALUES ('1301','København K');
INSERT INTO CITY VALUES ('2000','Frederiksberg');
INSERT INTO CITY VALUES ('2100','København Ø');

INSERT INTO PHONETYPE VALUES ('1','Privat');
INSERT INTO PHONETYPE VALUES ('2','Arbejde');