notifications:
  slack: dat3-fall-2020:FD0Eo9xmcFuxzFmTAnpZco3x
  email: false

dist: focal

language: java

cache:
  directories:  
    - $HOME/.m2

script:
  - mvn test
  - if [[ $TRAVIS_BRANCH == 'master' ]]; then mvn -Dremote.user=$REMOTE_USER -Dremote.password=$REMOTE_PW tomcat7:deploy; fi

services:
   - mysql

before_script:
- sudo apt-get update || true
- sudo apt-get install -y debconf-utils
- sudo debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/select-server select mysql-8.0'
- wget https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb
- sudo -E dpkg -i mysql-apt-config_0.8.13-1_all.deb
- sudo apt-get update || true

- echo "Installing MySQL 8..."
- sudo -E apt-get -y install mysql-server

- sudo mysql -u root -e "CREATE User 'dev'@'localhost' IDENTIFIED BY 'ax2'; GRANT ALL PRIVILEGES ON *.* TO 'dev'@'localhost' WITH GRANT OPTION;"
- sudo mysql -u dev -pax2 -e "CREATE DATABASE CA1_test;"

- mysql --version
- echo "before_script Complete"
